version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
    ports:
      - '4566-4597'
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  test-runner:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks:
      - default
    volumes:
      - ./app:/app/app
    command: ["sh", "-c", "python -m unittest"]